### ISSUE TITLE
Wrong listing of server ?

### ISSUE THREAD

**Issue by pierre-sepulchre** [PBrockmann/simuFinder#4]
Listing of vesg.ipsl.upmc.fr/thredds/catalog/work server does not seem to work properly.

There might be a "*" missing in [create_list.bash](https://github.com/PBrockmann/simuFinder/blob/master/create_list.bash) file, line 20: 
`ls -d1 /ccc/work/cont003/dods/public/*/*/*/*/MONITORING`

**Comment by PBrockmann** [comment]
Simulations monioring can be found with 4 levels after the login
ls -d1 /ccc/work/cont003/dods/public/*/*/*/*/MONITORING 
and also 5 levels after the login as in
ls -d1 /ccc/work/cont003/dods/public/*/*/*/*/*/MONITORING

simuFinder scans now both.
